# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: WWW Frontend Github Action Pipeline

on:
  push:
    branches:
      - develop

jobs:
  publish-aws-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules  # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-develop-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Create Environment File
        env:
          KAKAO_MAP_KEY: ${{ secrets.KAKAO_MAP_KEY }}
        run: |
          echo $KAKAO_MAP_KEY >> .env
          cat .env

      - name: Install Dependencies # 의존성 설치
        run: yarn install

      - name: Build Yarn Build
        run: yarn build

      - name: Console Output File List
        run: ls -al

      - name: Current Path
        run: |
          pwd
          ls dist

      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'dist'
          
      - name: CloudFront Cache Invalidation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-2'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E37FOS401R4E40 \
            --paths "/*"